/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Ultralight.h
 #	source generated by 4D Plugin Wizard
 #	Project : Ultralight
 #	author : miyako
 #	2019/09/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ULTRALIGHT_H
#define PLUGIN_ULTRALIGHT_H

#include "4DPluginAPI.h"
#include "IFileSystem.hpp"
#include <iostream>
#include <string>
#include <memory>

#pragma mark -

void Ultralight_Test(PA_PluginParameters params);

#endif /* PLUGIN_ULTRALIGHT_H */
