/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Ultralight.h
 #	source generated by 4D Plugin Wizard
 #	Project : Ultralight
 #	author : miyako
 #	2019/09/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ULTRALIGHT_H
#define PLUGIN_ULTRALIGHT_H

#include "4DPluginAPI.h"

#include "C_BLOB.h"

#include "png.h"
#define INCHES_PER_METER (100.0/2.54)

#include "4DPlugin-JSON.h"

#include "IFileSystem.hpp"

#pragma mark -

void Ultralight_Create_view(PA_PluginParameters params);
void Ultralight_Load_html(PA_PluginParameters params);
void Ultralight_Load_path(PA_PluginParameters params);
void Ultralight_Get_snapshot(PA_PluginParameters params);
void Ultralight_Evaluate_script(PA_PluginParameters params);

#endif /* PLUGIN_ULTRALIGHT_H */
